server:
  port: 8766
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.113:1001/eureka/

spring:
  application:
    name: car-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.113:3306/classroom?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://localhost:27017/1809a

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000
    pool:
      max-active: 1000
      max-wait: -1
      max-idle: 10
      min-idle: 5

mybatis:
  mapper-locations: classpath:mapper/*.xml

